name: testing

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: make setup

      - name: Run linter
        run: make lint

      - name: Run test
        run: make test
